name: TheBridge
version: 3.0.0
api: [4.0.0]
main: bridge\Main
author: Chr4st
description: Project Promise's The Bridge Plugin
commands:
 tb:
  description: "TheBridge Main Commands!"

permissions:
  tb.cmd:
    description: "Allows you to use all TheBridge commands"
  tb.pos1:
    description: "Allows you use /tb pos1 command."
  tb.pos2:
    description: "Allows you use /tb pos2 command."
  tb.spawn1:
    description: "Allows you use /tb spawn1 command."
  tb.spawn2:
    description: "Allows you use /tb spawn2 command."
  tb.respawn1:
    description: "Allows you use /tb respawn1 command."
  tb.respawn2:
    description: "Allows you use /tb respawn2 command."
  tb.spawn:
    description: "Allows you use /tb spawn command."
  tb.leaderboard:
    description: "Allows you use /tb leaderboard command."
  tb.npc:
    description: "Allows you use /tb npc command."